# Form implementation generated from reading ui file 'c:\Users\PC\Documents\GitHub\SimpleMidiEditor\SimpleMIDI\QTFiles\HelpPage.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1140, 661)
        Dialog.setStyleSheet("QDialog {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:2, y2:2, stop:0 rgba(0, 0, 0, 50), stop:1 rgba(255, 255, 255, 50))}\n"
"\n"
"QFrame {background-color: rgb(40,40,40)}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 86, 641))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.GeneralPageButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneralPageButton.sizePolicy().hasHeightForWidth())
        self.GeneralPageButton.setSizePolicy(sizePolicy)
        self.GeneralPageButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 50), stop:1 rgba(255, 255, 255, 50))")
        self.GeneralPageButton.setDefault(False)
        self.GeneralPageButton.setFlat(False)
        self.GeneralPageButton.setObjectName("GeneralPageButton")
        self.verticalLayout_2.addWidget(self.GeneralPageButton)
        self.CanvasPageButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.CanvasPageButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 50), stop:1 rgba(255, 255, 255, 50))")
        self.CanvasPageButton.setDefault(False)
        self.CanvasPageButton.setFlat(False)
        self.CanvasPageButton.setObjectName("CanvasPageButton")
        self.verticalLayout_2.addWidget(self.CanvasPageButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainTab = QtWidgets.QStackedWidget(parent=Dialog)
        self.MainTab.setObjectName("MainTab")
        self.GeneralThemePage = QtWidgets.QWidget()
        self.GeneralThemePage.setObjectName("GeneralThemePage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.GeneralThemePage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.GeneralThemePage)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1006, 592))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.MainTab.addWidget(self.GeneralThemePage)
        self.CanvasPage = QtWidgets.QWidget()
        self.CanvasPage.setObjectName("CanvasPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.CanvasPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(parent=self.CanvasPage)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setIndent(4)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.MainTab.addWidget(self.CanvasPage)
        self.verticalLayout.addWidget(self.MainTab)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.MainTab.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.GeneralPageButton.setText(_translate("Dialog", "General"))
        self.CanvasPageButton.setText(_translate("Dialog", "Canvas"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>Upper dock(Note edit)</p><p>    - Upper dock contains tools to edit notes.</p><p>    - Left side is used to select mode between Place/Remove.</p><p>    - Right side is used to pick an instrument from standart MIDI library.</p><p>- Lower dock(General)</p><p>    - Right side contains playback controls.</p><p>    - Left side contains visual grid size settings [X; Y] and onion skin settings.</p><p>- Right dock(Logger)</p><p>    - This dock displays warnings if settings</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Canvas\n"
"    - Hold left mouse button to move around.\n"
"    - To place notes: select \"Place\" edit mode, hold right mouse button where you want to place the note and drag cursor to set its length\n"
"    - To delete notes: select \"Remove\" edit mode, click the notes [!On the same layer/instrument index!] to remove them.\n"
"    - Upper text marks show time position of the grid x\n"
"    - Side text marks show pitch of the grid y"))
