# Form implementation generated from reading ui file 'QTFiles/HelpPage.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelpPageDialog(object):
    def setupUi(Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1140, 661)
        Dialog.setStyleSheet("QDialog {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:2, y2:2, stop:0 rgba(0, 0, 0, 50), stop:1 rgba(255, 255, 255, 50))}\n"
"\n"
"QFrame {background-color: rgb(40,40,40)}")
        Dialog.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        Dialog.horizontalLayout.setObjectName("horizontalLayout")
        Dialog.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.scrollArea.sizePolicy().hasHeightForWidth())
        Dialog.scrollArea.setSizePolicy(sizePolicy)
        Dialog.scrollArea.setWidgetResizable(True)
        Dialog.scrollArea.setObjectName("scrollArea")
        Dialog.scrollAreaWidgetContents = QtWidgets.QWidget()
        Dialog.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 86, 641))
        Dialog.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        Dialog.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog.scrollAreaWidgetContents)
        Dialog.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        Dialog.verticalLayout_2.setObjectName("verticalLayout_2")
        Dialog.GeneralPageButton = QtWidgets.QPushButton(parent=Dialog.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.GeneralPageButton.sizePolicy().hasHeightForWidth())
        Dialog.GeneralPageButton.setSizePolicy(sizePolicy)
        Dialog.GeneralPageButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 50), stop:1 rgba(255, 255, 255, 50))")
        Dialog.GeneralPageButton.setDefault(False)
        Dialog.GeneralPageButton.setFlat(False)
        Dialog.GeneralPageButton.setObjectName("GeneralPageButton")
        Dialog.verticalLayout_2.addWidget(Dialog.GeneralPageButton)
        Dialog.CanvasPageButton = QtWidgets.QPushButton(parent=Dialog.scrollAreaWidgetContents)
        Dialog.CanvasPageButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 50), stop:1 rgba(255, 255, 255, 50))")
        Dialog.CanvasPageButton.setDefault(False)
        Dialog.CanvasPageButton.setFlat(False)
        Dialog.CanvasPageButton.setObjectName("CanvasPageButton")
        Dialog.verticalLayout_2.addWidget(Dialog.CanvasPageButton)
        Dialog.scrollArea.setWidget(Dialog.scrollAreaWidgetContents)
        Dialog.horizontalLayout.addWidget(Dialog.scrollArea)
        Dialog.verticalLayout = QtWidgets.QVBoxLayout()
        Dialog.verticalLayout.setObjectName("verticalLayout")
        Dialog.MainTab = QtWidgets.QStackedWidget(parent=Dialog)
        Dialog.MainTab.setObjectName("MainTab")
        Dialog.GeneralThemePage = QtWidgets.QWidget()
        Dialog.GeneralThemePage.setObjectName("GeneralThemePage")
        Dialog.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog.GeneralThemePage)
        Dialog.verticalLayout_3.setObjectName("verticalLayout_3")
        Dialog.scrollArea_2 = QtWidgets.QScrollArea(parent=Dialog.GeneralThemePage)
        Dialog.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        Dialog.scrollArea_2.setWidgetResizable(True)
        Dialog.scrollArea_2.setObjectName("scrollArea_2")
        Dialog.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        Dialog.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1006, 592))
        Dialog.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        Dialog.verticalLayout_6 = QtWidgets.QVBoxLayout(Dialog.scrollAreaWidgetContents_2)
        Dialog.verticalLayout_6.setObjectName("verticalLayout_6")
        Dialog.verticalLayout_5 = QtWidgets.QVBoxLayout()
        Dialog.verticalLayout_5.setObjectName("verticalLayout_5")
        Dialog.label_6 = QtWidgets.QLabel(parent=Dialog.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.label_6.setFont(font)
        Dialog.label_6.setStyleSheet("color: rgb(255, 255, 255)")
        Dialog.label_6.setWordWrap(True)
        Dialog.label_6.setObjectName("label_6")
        Dialog.verticalLayout_5.addWidget(Dialog.label_6)
        Dialog.verticalLayout_6.addLayout(Dialog.verticalLayout_5)
        Dialog.scrollArea_2.setWidget(Dialog.scrollAreaWidgetContents_2)
        Dialog.verticalLayout_3.addWidget(Dialog.scrollArea_2)
        Dialog.MainTab.addWidget(Dialog.GeneralThemePage)
        Dialog.CanvasPage = QtWidgets.QWidget()
        Dialog.CanvasPage.setObjectName("CanvasPage")
        Dialog.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog.CanvasPage)
        Dialog.verticalLayout_4.setObjectName("verticalLayout_4")
        Dialog.frame_5 = QtWidgets.QFrame(parent=Dialog.CanvasPage)
        Dialog.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        Dialog.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        Dialog.frame_5.setObjectName("frame_5")
        Dialog.horizontalLayout_6 = QtWidgets.QHBoxLayout(Dialog.frame_5)
        Dialog.horizontalLayout_6.setObjectName("horizontalLayout_6")
        Dialog.label_2 = QtWidgets.QLabel(parent=Dialog.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.label_2.setFont(font)
        Dialog.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        Dialog.label_2.setScaledContents(False)
        Dialog.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        Dialog.label_2.setWordWrap(True)
        Dialog.label_2.setIndent(4)
        Dialog.label_2.setOpenExternalLinks(False)
        Dialog.label_2.setObjectName("label_2")
        Dialog.horizontalLayout_6.addWidget(Dialog.label_2)
        Dialog.verticalLayout_4.addWidget(Dialog.frame_5)
        Dialog.MainTab.addWidget(Dialog.CanvasPage)
        Dialog.verticalLayout.addWidget(Dialog.MainTab)
        Dialog.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        Dialog.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        Dialog.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        Dialog.buttonBox.setObjectName("buttonBox")
        Dialog.verticalLayout.addWidget(Dialog.buttonBox)
        Dialog.horizontalLayout.addLayout(Dialog.verticalLayout)

        Ui_HelpPageDialog.retranslateUi(Dialog)
        Dialog.MainTab.setCurrentIndex(0)
        Dialog.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        Dialog.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        Dialog.GeneralPageButton.setText(_translate("Dialog", "General"))
        Dialog.CanvasPageButton.setText(_translate("Dialog", "Canvas"))
        Dialog.label_6.setText(_translate("Dialog", "<html><head/><body><p>Upper dock(Note edit)</p><p>    - Upper dock contains tools to edit notes.</p><p>    - Left side is used to select mode between Place/Remove.</p><p>    - Right side is used to pick an instrument from standart MIDI library.</p><p>- Lower dock(General)</p><p>    - Right side contains playback controls.</p><p>    - Left side contains visual grid size settings [X; Y] and onion skin settings.</p><p>- Right dock(Logger)</p><p>    - This dock displays warnings if settings</p></body></html>"))
        Dialog.label_2.setText(_translate("Dialog", "Canvas\n"
"    - Hold left mouse button to move around.\n"
"    - To place notes: select \"Place\" edit mode, hold right mouse button where you want to place the note and drag cursor to set its length\n"
"    - To delete notes: select \"Remove\" edit mode, click the notes [!On the same layer/instrument index!] to remove them.\n"
"    - Upper text marks show time position of the grid x\n"
"    - Side text marks show pitch of the grid y"))
