# Form implementation generated from reading ui file 'c:\Users\PC\Documents\GitHub\SimpleMidiEditor\SimpleMIDI\QTFiles\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(512, 399)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 104, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InterfacePageButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterfacePageButton.sizePolicy().hasHeightForWidth())
        self.InterfacePageButton.setSizePolicy(sizePolicy)
        self.InterfacePageButton.setDefault(False)
        self.InterfacePageButton.setFlat(False)
        self.InterfacePageButton.setObjectName("InterfacePageButton")
        self.verticalLayout_2.addWidget(self.InterfacePageButton)
        self.TestPageButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.TestPageButton.setObjectName("TestPageButton")
        self.verticalLayout_2.addWidget(self.TestPageButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainTab = QtWidgets.QStackedWidget(parent=Dialog)
        self.MainTab.setObjectName("MainTab")
        self.InterfaceThemepage = QtWidgets.QWidget()
        self.InterfaceThemepage.setObjectName("InterfaceThemepage")
        self.label = QtWidgets.QLabel(parent=self.InterfaceThemepage)
        self.label.setGeometry(QtCore.QRect(280, 100, 47, 13))
        self.label.setObjectName("label")
        self.MainTab.addWidget(self.InterfaceThemepage)
        self.TestPage = QtWidgets.QWidget()
        self.TestPage.setObjectName("TestPage")
        self.label_2 = QtWidgets.QLabel(parent=self.TestPage)
        self.label_2.setGeometry(QtCore.QRect(150, 250, 47, 13))
        self.label_2.setObjectName("label_2")
        self.MainTab.addWidget(self.TestPage)
        self.verticalLayout.addWidget(self.MainTab)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.MainTab.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.InterfacePageButton.setText(_translate("Dialog", "Interface theme"))
        self.TestPageButton.setText(_translate("Dialog", "PushButton"))
        self.label.setText(_translate("Dialog", "this is interface settings"))
        self.label_2.setText(_translate("Dialog", "This is test page!!"))
